### ISSUE TITLE
Mapping EF child collection of entities with Identity

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [leonardoporro/Detached-Mapper#68] opened 2023-01-23 06:39 UTC
I am having root entity in EF that has a few children. Some children have explicit keys and they mapped/populated as expected. 
One child has Identity primary key, and it is not mapped and cause errors: 
The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded.
My code is just
 `var entity = await dataContext.MapAsync<RootEntity>(dataModel);`
In dataModel I have fields populated 

"ChildrenWithIdentity": [
          {
            "Id": 0,
            "ItineraryId": 73551,
            "PopulatedProperty": "EzgybP6Y4qApGZYyA0Hqvw==",
          }
        ]
 but in mapped entity key is also 0 ,but properties are not copied
"ChildrenWithIdentity": [
          {
            "Id": 0,
            "ItineraryId": 0,
          //Properties are null
          }
        ]
        
Do you support  child entities with GeneratedOption.Identity? 
If yes, can you suggest what else can be wrong with my ChildrenWithIdentity ?
Is any tracing can be enabled that explain why mapping for this child doesn't work ?

Tor now, I've excluded ChildrenWithIdentity property by calling entity.ChildrenWithIdentity .Clear(),and  process the children manually. Can you suggest other way to exclude children properties from map?

Example of my schema
 public class RootEntity
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]  
        public int ItineraryId { get; set; }

        //Navigation Properties
        public List<WorkingChild> WorkingChildren{ get; set; }
 
        public List<ChildWithIdentity> ChildrenWithIdentity{ get; set; }
}
For children that have known keys MapAsync works ok,
But for table with autogenrated ID it creates object with no properties

public class WorkingChild
    {
        [Key, Required, DatabaseGenerated(DatabaseGeneratedOption.None)]//No IDENTITY
        public int ComponentId { get; set; }
  public int ItineraryId { get; set; }
//other properties
        }
  public class ChildWithIdentity
    {
       
      [Key, Required,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id{ get; set; }
  public int ItineraryId { get; set; }
//other properties
}

**Comment by leonardoporro** [comment] 2023-01-23 17:50
Hi @michael-freidgeim-webjet,
thanks for trying the library and for the feedback
this sample works for me, could you please edit it to reproduce your  scenario?

```csharp
// See https://aka.ms/new-console-template for more information
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;
using Detached.Annotations;
using Detached.Mappers.EntityFramework;
using System.Diagnostics;

using (AppDbContext dbContext = new AppDbContext())
{
    dbContext.Map<RootEntity>(new RootEntity
    {
        WorkingChildren = new List<WorkingChild>
        {
            new WorkingChild { ComponentId = 1 },
            new WorkingChild { ComponentId = 2 }
        },
            ChildrenWithIdentity = new List<ChildWithIdentity>
        {
            new ChildWithIdentity { ItineraryId = 3 },
            new ChildWithIdentity { ItineraryId = 4 }
        }
    });

    dbContext.Database.EnsureDeleted();
    dbContext.Database.EnsureCreated();
    dbContext.SaveChanges();
}

using (AppDbContext dbContext = new AppDbContext())
{
    RootEntity? rootentity = dbContext
        .RootEntities
        .Include(r => r.ChildrenWithIdentity)
        .Include(r => r.WorkingChildren)
        .FirstOrDefault();

    Debug.Assert(rootentity.ChildrenWithIdentity != null && rootentity.ChildrenWithIdentity.Count == 2);
    Debug.Assert(rootentity.WorkingChildren != null && rootentity.WorkingChildren.Count == 2);
}


Console.WriteLine("Hello, World!");


public class RootEntity
{
    [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int ItineraryId { get; set; }

    [Composition]
    public List<WorkingChild> WorkingChildren { get; set; }

    [Composition]
    public List<ChildWithIdentity> ChildrenWithIdentity { get; set; }
}

public class WorkingChild
{
    [Key, Required, DatabaseGenerated(DatabaseGeneratedOption.None)]//No IDENTITY
    public int ComponentId { get; set; }

    public int ItineraryId { get; set; }
    //other properties
}
public class ChildWithIdentity
{

    [Key, Required, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }
    public int ItineraryId { get; set; }
    //other properties
}

public class AppDbContext : DbContext
{
    public DbSet<RootEntity> RootEntities { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Data Source=.;Initial Catalog=myDataBase;User ID=sa;Password=ThisIsMyPassword2023;Trust Server Certificate=true;")
                      .UseMapping();
    }
}
```

**Comment by MNF** [comment] 2023-01-29 00:49
I wasn’t able to make MapAsync working for  my model. If child model is new, MapAsync creates new entity with all default fields(nulls or 0) instead of copy properties.
My child entity has composed key ItineraryId+  PassengerId 
 
Example that doesn’t work:
New model child, where PassengerId  1 exists and PassengerId  2 doesn’t exist in the database.
            "Passengers": [
              {
                "PassengerId": 1,
                "ItineraryId": 73551,
                "Salutation": "MRS",
                "FirstMiddleName": "Janet",
                "PassengerSequence": 0
              },
              {
                "PassengerId": 2,
                "ItineraryId": 73551,
                "Salutation": "MR",
                "FirstMiddleName": "Micheal",
                "PassengerSequence": 0
              }
            ],
            
MappedEntity  "Passengers": [
              {
                "PassengerId": 1,
                "ItineraryId": 73551,
                "Salutation": "MRS",
                "FirstMiddleName": "Janet",
                "PassengerSequence": 0,
                "ItineraryListRow": {
                  "$ref": "1"
                }
              },
              {
                "PassengerId": 2,
                "ItineraryId": 0,
                "PassengerSequence": 0
              }
            ],

Unfortunately, I don’t have time now to create minimal working example to reproduce the problem for you.

I was able to make my model working using different package 
https://github.com/WahidBitar/EF-Core-Simple-Graph-Update

**Comment by leonardoporro** [comment] 2023-01-29 03:00
Have you tested the sample I sent?
Did you add [Composition] attribute to the props containing the children you want to update?
That Json is a bit confusing...  You just need to send the classes, not an entire working (or not working) example.

**Comment by leonardoporro** [comment] 2023-02-10 11:06
Hi @MNF 
Good that you was able to make it work with [EF-Core-Simple-Graph-Update](https://github.com/WahidBitar/EF-Core-Simple-Graph-Update).
Sorry, there is 0 budget for this project and it is out of my possibilities to reconstruct issues from narratives or pieces of code.
If you are interested in trying again, please send me your model classes and I will gladly make it work for you.  
For models under any NDA you may send it directly to me by email.
Closing, for the moment...

**Closed by leonardoporro** 2023-02-10 11:06 UTC
