### ISSUE TITLE
Aggregation doesn't seem to work properly

### ISSUE THREAD

**Issue by traiannemes** [leonardoporro/Detached-Mapper#92] opened 2023-06-08 03:02 UTC
**Describe the bug**
[ConsoleApp1.zip](https://github.com/leonardoporro/Detached-Mapper/files/11683641/ConsoleApp1.zip) 
Aggregation doesn't seem to work properly

**To Reproduce**
Copy/past this code into a console app or use the zip file attached
```
using Detached.Annotations;
using Detached.Mappers.EntityFramework;
using Microsoft.EntityFrameworkCore;

var context = new AppDbContext();

var organization = new Organization() { OrganizationName = "Tesla" };
var organization2 = new Organization() { OrganizationName = "Tesla2" };

context.Add(organization);
context.Add(organization2);
await context.SaveChangesAsync();
context.ChangeTracker.Clear();

var organizationFromDb1 = context.Organizations.First(x => x.OrganizationName == "Tesla");
var user = new User() { FirstName = "FirstName", LastName = "Last Name", Organization = organizationFromDb1 };

await context.MapAsync<User>(user);
await context.SaveChangesAsync();
context.ChangeTracker.Clear();

var userFromDb = context.Users
    .Include(x => x.Organization)
    .First(x => x.FirstName == "FirstName");
var organizationFromDb2 = context.Organizations.First(x => x.OrganizationName == "Tesla2");
context.ChangeTracker.Clear();

userFromDb.LastName = "Test";
userFromDb.Organization = organizationFromDb2;
userFromDb.OrganizationId = organizationFromDb2.OrganizationId;

var userFromDb2 = await context.MapAsync<User>(userFromDb); //after this line User.Organization is empty except the primary key, no matter how many other properties has

await context.SaveChangesAsync();

// Inspect userFromDb2 and see if Organization Name is populated
var test = userFromDb2;


public class Organization
{
    public int OrganizationId { get; set; }
    public string OrganizationName { get; set; } = null!;
}
public class User
{
    public int UserId { get; set; }

    public int? OrganizationId { get; set; }

    [Aggregation]
    public Organization? Organization { get; set; }

    public string FirstName { get; set; } = null!;

    public string LastName { get; set; } = null!;

}


public class AppDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=.;Database=TestDb;Trusted_Connection=True;Trust Server Certificate=true;");
        optionsBuilder.UseDetached();
        base.OnConfiguring(optionsBuilder);
    }
    public virtual DbSet<Organization> Organizations { get; set; }
    public virtual DbSet<User> Users { get; set; }
}
```

**Comment by traiannemes** [comment] 2023-07-12 02:20
Hi @leonardoporro, just checking, are you in summer vacation or away for a bit? Thanks

**Comment by leonardoporro** [comment] 2023-07-13 01:52
Hi @traiannemes, starting on a new job and taking care of my 11 months son who went through an open heart surgery and now he needs a small adjustment.
But haven't forgot this project, planning to push a major update with lot of bugfixing during the next 15 days.
Sorry for the delays

**Comment by traiannemes** [comment] 2023-07-13 02:02
Oh man, sorry to hear that, all our best wishes to your son, make him strong to go through this! Really no rush, and if there's anything we can do from a distance, let us know.

**Comment by leonardoporro** [comment] 2023-07-26 14:59
Hey, slowly going back on track! Sorry for the long long long delay...

I was able to run your sample, by the way thanks! attaching a sample helps me so much
In your sample, User.Organization.Name is populated:
![image](https://github.com/leonardoporro/Detached-Mapper/assets/4844092/72334672-173c-41e2-8dcb-d35af34a4457)
But I know what are you talking about and why it is happening, it is by design.

When a property is marked as [Aggregation] instead of [Composition], the mapper assumes that the entity being aggregated already exists.
That's the idea, if you have a User and, for example, you want to assign a UserType { Id, Name }, it is assumed that UserType { Id, Name } already exists, and handling it is not a part of the current operation.

Given that, the mapper just creates an entity, sets the primary key and marks it as Unchanged, so there is no need to go to the database to fetch the rest of the fields.
Also, as DTO you may send something like this: 
`
{
   userType: { id: 1 }
}
`
(that id would probably come from a dropdown list or something similar)

There is a flag [here](https://github.com/leonardoporro/Detached-Mapper/blob/3b72d99f20fff7ef571e4df095e86d8b7faf84ba/src/Detached.Mappers/MapParameters.cs#L10C2-L10C2) that allows aggregations work as an Upsert. It is internally used when importing Json files so you don't need to ensure the (for example) UserType exists before User, because it does a UserType upsert.
I don't recommend it because it goes to the DB and here I'm trying to fetch as few data as possible. Having to querying for the item and the compositions is already slow enough.

There is some info about aggregations [here](https://github.com/leonardoporro/Detached-Mapper/wiki/Associations).
And [here](https://github.com/leonardoporro/Detached-Mapper/wiki/Foreign-Keys) you can check how an association is done without having the attached entity.

Hope this info helps and let me know if you need anything else!

**Comment by traiannemes** [comment] 2023-07-26 15:26
Morning Leonardo,

I am at a lose, here is my screenshot on the same code

![image](https://github.com/leonardoporro/Detached-Mapper/assets/17482503/4657dfc0-6dbe-4bc2-8bb6-925f656fe49c)

The real work example is something like this

![image](https://github.com/leonardoporro/Detached-Mapper/assets/17482503/bd4ccd0a-72a5-4a0b-ade1-256eb3108148)

User class has an Organization aggregation, which has a name. I just save the user and want to return newUser back to API caller with all the info. It saves me a call to 

![image](https://github.com/leonardoporro/Detached-Mapper/assets/17482503/45296d78-2031-4544-8bcc-11f5a38fd533)

I am using that user object to refresh a row in the data grid (presentation layer, client for API)

**Comment by leonardoporro** [comment] 2023-07-26 15:38
![devenv_QIcBAYDchj](https://github.com/leonardoporro/Detached-Mapper/assets/4844092/97f80f4d-1016-4518-b54b-459247326c8b)

weird!
I know how to reproduce it anyway.. let me do it and see if it can be improved.

**Comment by traiannemes** [comment] 2023-07-26 15:53
That's totally weird! I can only say that I tried on two difference laptops and one PC, all with VS2022.

**Comment by leonardoporro** [comment] 2023-07-26 16:21
7.1.3

**Comment by traiannemes** [comment] 2023-07-26 17:23
It's working like a charm, thank you sir!

**Closed** 2023-07-26 17:54 UTC
