### ISSUE TITLE
Unable to find package

### ISSUE THREAD

**Issue by pinoli** [leonardoporro/Detached-Mapper#19] opened 2020-10-19 23:59 UTC
Hi,
I decided to give Detached a try, but when trying to install it in my current project I get

```
PM> Install-Package Detached.Mappers.EntityFramework
Install-Package : Unable to find package 'Detached.Mappers.EntityFramework'
At line:1 char:1
+ Install-Package Detached.Mappers.EntityFramework
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:03.7855917
```

It seems it's not present on the Nuget package Manager. Any workaround?

**Comment by leonardoporro** [comment] 2020-10-20 02:18
Hi @pinoli, thank you for giving a try
I installed it using 
`Install-Package Detached.Mappers.EntityFramework -Version 5.0.0-rc.2.20475.6`
 and worked well.
Do you have VS 2019 and net 5 installed?
This package is built using EF Core 5 preview (since it seems to be the first decent version of EF Core).
I saw over here (https://github.com/dotnet/efcore/issues/23044) that you have the same problem as me and many other people. I'll be glad to help if you provide a bit more of context.

**Comment by pinoli** [comment] 2020-10-20 16:08
Thank you very much Leonardo for your support.
Yesterday I managed to get the correct version anyway, thanks for updating the project though.
Unfortunately I stumbled upon another unrelated issue: my project could not work because it is an Azure Function, and Functions don't support net5 yet (it's planned but there is no ETA).

I am intrigued by your library because it *looks* like what I need, but I need to test it thouroghly. Since it will not work with Azure Functions, I am planning on adapting my code to your sample project, to at least see if I can get what I need.

Finally, I can tell you something more about my specific issue. I need to call an API returning many, deeply nested objects with many of shared children (at every level). These objects have their own primary keys and relationships. The first struggle, when the DB is empty, is to create the Local context, since if I simply add every parent, I am actually adding loads of identical objects, with the same key,  deeply nested in the parents.
Then, after the DB is populated, every time I call the API to update the DB, I need to check if any children is already present in the local context (objects in the API response) and in the dbcontext (objects already in the DB).
On top of that, I need to have a mechanism to check if the entity needs to be updated if found in the context: in my case I achieve it using lastUpdated property in (almost) every object the API returns.
Also, but this is specific to this API, many objects have list of children with no key; this complicates further since I cant store objects with no key in the DB while keeping all the relationships.

Thanks for your support, I hope I can use Detached in my projects.

**Comment by leonardoporro** [comment] 2020-10-20 23:58
I managed to downgrade it to 3.1.9 with some minor fixes.
Tests passed ok, but I didn't try it on a real system.
`Install-Package Detached.Mappers.EntityFramework -Version 3.1.9`
Let me know if it helps.
Regarding your specific issue, I think  that the library can help. It builds an expression tree, just like automapper, then it calls  IMapperContext (EntityFrameworkMappingContext) for each entity, to load/update/delete it. That can be customized.
Other mapping and reflection tools might be useful too.
Also for objects with no keys, a "virtual" property might be added to the mapper configuration, with an expression that computes the hash of all the other properties. Maybe the new Record Type in C# 9.0 may help too.
Let me know your toughts.
I'll close this issue if the packages work ok.

**Comment by pinoli** [comment] 2020-10-22 04:30
I updated my testbench solution to work with the updated version (3.1.9), it now works. Thank you very much.
I am able to add every object received from the API, but when I try to call `context.SaveChangesAsync()` I get this error:
```
An error occurred while updating the entries. See the inner exception for details. Core Microsoft SqlClient Data Provider: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Receipts_Documents_DocumentId". The conflict occurred in database "detached", table "dbo.Documents", column 'Id'.
```
It's weird because this is the first time I am seeing this kind of error with this data and EF Core.
I know that without knowing the object details, but if you have something in mind please let me know.

Thanks again.

**Comment by pinoli** [comment] 2020-10-22 04:38
@leonardoporro I realized that `.MapAsync()` doesn't add children when mapping a parent object.
The error above is caused by the fact that when saving to db, the parent objects had foreign keys for children that did not exist in the db.

Is there a way to do this, or do I need to traverse the object manually and call `.MapAsync()` for each leaf in the object hierarchy?
Thanks

**Comment by leonardoporro** [comment] 2020-10-22 12:52
Did you mark the children that you want to be added as Compositions? That can be done with the [Composition] attribute, or using mapping options parameter for UseDetached method.
The logic is similar to GraphDiff: Aggregations are weak associations, i.e.: references to entities that can exist by themselves, so that, they are not created or deleted with the root entity. Compositions are strong references, and are created/deleted with the root.
There is also a hidden parameter in MapperParameters:
       ` /// <summary>
        /// If true, non-existing aggregtions are created.
        /// </summary>
        public bool EnsureAggregations { get; set; } = false;`
This forces aggregations state to be set to Add if they don't exist.
Associations that are not marked as Composition or Aggregation are not mapped.

**Comment by pinoli** [comment] 2020-10-22 17:09
hi @leonardoporro thanks for the clarification. I am playing with `[Aggregation]` and `[Composition]` to see If i get the desired results. If I set every children to `[Composition]` i get the following error from Detached
```
System.Private.CoreLib: Exception while executing function: TestDetached. Detached.Mappers: Can't construct bool. It does not have a parameterless constructor or a concrete type specified.
```
Also, where should I set the `EnsureAggregations` parameter if I wanted to try it?
Finally, you say `There is a feature to import Json files using merge`. Can you expand a bit?

thanks for your support

**Comment by leonardoporro** [comment] 2020-10-22 18:30
Did you add a [Composition] attribute over a bool property? "Can't construct bool" looks like it is handing a bool like a complex type.

To set EnsureAggregations, use MapperParameters:
`await MapAsync<TEntity>(dbContext, entity, new MapperParameters { EnsureAggregations = true });`

There is an ImportJsonAsync extension method, that receives json and "attaches" it to the context using Detached mechanism.
It only updates properties that appear on the json file. 
There is a sample feature test [here](https://github.com/leonardoporro/Detached-Mapper/blob/main/test/Detached.Mappers.EntityFramework.Tests/ImportTests.cs)

The partial updates are implemented by deserializing the json to a special Patch proxy type. The patch type inherites the entity and implements IPatch interface, to track what properties has changed. So that, it needs the properties to be marked as virtual to work. This only applies to Import. Map doesn't require any special treatment for properties.

**Comment by pinoli** [comment] 2020-10-22 18:56
`Did you add a [Composition] attribute over a bool property? "Can't construct bool" looks like it is handing a bool like a complex type.`

this is the first thing I check, unfortunately no `bool` properties are marked as `[Composition]` or `[Aggregation]`.
I carefully review each object in the model, set `[Entity]` in every object and also added `new MapperParameters { EnsureAggregations = true }` to my MapAsync call.

As I told you, I have some nested object with no key, and as a workaround I generate the Guid when creating a new istance.
**object constructor**
```
        public Object()
        {
            Id = Guid.NewGuid();
        }
```

**object id settings**
```
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid Id { get; set; }
```

I am unfortunately still getting the same message
```
Detached.Mappers: Can't construct bool. It does not have a parameterless constructor or a concrete type specified.
```
Should I open a new issue? Thanks

**Comment by leonardoporro** [comment] 2020-10-22 20:21
Please, open a new one. Could you provide some sample model?

**Comment by leonardoporro** [comment] 2020-10-23 00:00
PS: You can add more values to primitives, for example, an ObjectId from MongoDB library... Values added as primitive are copied as is, and not property by property.
I need to write a lot of documentation...

**Comment by pinoli** [comment] 2020-10-23 03:34
thanks alot @leonardoporro I just updated to 3.1.10 and the error disappeared...
Only to be replaced with a new error 😥
```
 System.Private.CoreLib: Exception while executing function: TestDetached. Detached.Mappers: Can't construct VariationType. It does not have a parameterless constructor or a concrete type specified.
```
It's exactly like the previous one, but the type is `VariationType`. Now, I checked and I don't use it directly, but I can tell I am using an `enum` in one of the children.

**Comment by pinoli** [comment] 2020-10-23 03:50
hey @leonardoporro thank you very much, the problem disappeared after updating to 3.1.10
I also noticed I could not use enums (and I was doing it in three different objects), otherwise I would get the same error I got for `bool` but with the enum type instead.

I am making progress 😊 Unfortunately, I am getting stuck while inserting keyless objects, as I shown before.
```
System.Private.CoreLib: Exception while executing function: TestDetached. Detached.Mappers: Indexer [System.Int32] doesn't exist in System.Collections.Generic.ICollection`1[TD.Models.RowModifier].
```

Basically this cose is giving me this error, and I don't know why.
```
 [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid Id { get; set; }
        public Object()
        {
            Id = Guid.NewGuid();
        }
```

it looks like Detached doesn't allow to do this.
If you know a workaround please let me know.

**Comment by pinoli** [comment] 2020-10-23 04:32
FYI I also tried the `ImportJsonAsync` method on serialized parent object, but I am getting this error
```
 System.Private.CoreLib: Exception while executing function: TestDetached. System.Text.Json: The JSON value could not be converted to System.Collections.Generic.IEnumerable`1[TD.Models.Receipt]. Path: $ | LineNumber: 0 | BytePositionInLine: 1
```
It's wierd since the JSON I receive is well formed and I can deserialize it onto my POCO objects, and serialize it back with no issue. It looks like it gets stuck at the first character.

**Comment by leonardoporro** [comment] 2020-10-23 05:03
Can't construct VariationType. It does not have a parameterless constructor or a concrete type specified.
:( same issue.. enums are also primitives.. fixed in 3.1.11

**Comment by leonardoporro** [comment] 2020-10-23 05:03
ImportJsonAsync: json should start with [ as it is expecting an array.

**Comment by leonardoporro** [comment] 2020-10-23 05:15
And about this one:
Indexer [System.Int32] doesn't exist in System.Collections.Generic.ICollection`1[TD.Models.RowModifier].

Detached only supports regular mutable List<>, when merging associated entities. 
This is because merging method doesn't always create a new collection, it adds or removes element to the current collection, using Add, and RemoveAt and iterating with a regular for and the indexer.

It looks like your collection doesn't have an indexer.

This is by design and helpful to integrate with other ORMs like Nhibernate. 

I don't see the point of using read only arrays or enumerations in an association. 
It would be very difficult to handle, requiring foreach and collection instance recreation.
If you know about an scenario that requires it, please let me know and I'll add the code fix.

Thanks for the debug feedback, I already added tests for the previous fixes

**Comment by leonardoporro** [comment] 2020-10-23 05:22
> hey @leonardoporro thank you very much, the problem disappeared after updating to 3.1.10
> I also noticed I could not use enums (and I was doing it in three different objects), otherwise I would get the same error I got for `bool` but with the enum type instead.
> 
> I am making progress 😊 Unfortunately, I am getting stuck while inserting keyless objects, as I've shown before.
> 
> ```
> System.Private.CoreLib: Exception while executing function: TestDetached. Detached.Mappers: Indexer [System.Int32] doesn't exist in System.Collections.Generic.ICollection`1[TD.Models.RowModifier].
> ```
> 
> Basically this code is giving me this error, and I don't know why. When I remove it, it doesn't throw this error, but EF complains (rightly) there is no key to establish a relationship with the parent object, where a navigation property to the keyless child is set.
> 
> ```
> [Key]
> [DatabaseGenerated(DatabaseGeneratedOption.None)]
> public Guid Id { get; set; }
> 
> public Object()
> {
>     Id = Guid.NewGuid()
> }
> ```
> 
> it looks like Detached doesn't allow to do this.
> If you know a workaround please let me know.

I think that Id is working ok, check my previous comment. Are you able to change the property type to List<> ?

**Comment by pinoli** [comment] 2020-10-23 21:58
@leonardoporro thanks for all your detailed responses.
I can tell you that with version 3.1.11 I can now get the API response and load it correctly in the DB, **this is amazing** and very promising for my current and future projects. It loaded all the objects correctly, leaving all the children and reletionships intact.
I also tried `ImportJsonAsync`, it works as well, very handy although I prefer to have control on the objects.

On the other hand I would like to ask you about a specific issue I am facing now and how to tackle it best with Detached.
**SCENARIO**
I have all my objects in the DB, I loaded 3 days worth of data.
Now imagine I want to load the next 3 days: I make an API call, deserialize new JSON to objects and call `MapAsync`. Up to this point everything works.
But when i call `SaveChangesAsync`, EF tells me (correctly) that I am trying to insert a duplicate object with the same foreign key, because many nested objects are already present in the DB. One of these conflicts arise with the User object: every Receipt (parent) has one of 3 users, in the first three days all 3 users were loaded as nested objects, but also the future Receipts will have one of these 3 User objects nested.

```
System.Private.CoreLib: Exception while executing function: TestDetached. Microsoft.EntityFrameworkCore.Relational: An error occurred while updating the entries. See the inner exception for details. Core Microsoft SqlClient Data Provider: Violation of PRIMARY KEY constraint 'PK_Users'. Cannot insert duplicate key in object 'dbo.Users'
```

I know very well this issue can be solved by using EF Core `EntityState`, but the reason I am testing Detached is to avoid this particular approach that doesn't play well with my situation.
What I imagine is something like `MergeAsync` where I receive new objects form the API and the method automatically reattaches or updates existing entities (it would be awesome if this could be set ), while at the same time adding every new objects. Like an Upsert, or something similar.

With pure EF Core, I need to traverse each child of the parent to accomplish this: check if child exists, attach existing or update, and repeat for every child in every parent of hundreds of parents with loads of nested objects. I am sure you know what I am talking about since you wrote Detached 😁

I don't know if you have any suggestion to adopt in this particular case, but this specific mechanism could make Detached an all in one solution to deal with EF Core greviences (until Microsoft decides it's time to include soemthing like this, contexts work well with UI apps where you control the data, but not so much where you need to reverse engineer an existing DB through an API).

I am glad I could help you sort out some issues, and let me know if you need something, I am constantly dealing with EF Core.
Thanks again for all your support, and sorry I hijacked your Issue section.

**Comment by leonardoporro** [comment] 2020-10-23 22:22
Hi again @pinoli 
Good, I'm glad you were able to sort out all of the library issues. 

If you look at this class:
`https://github.com/leonardoporro/Detached-Mapper/blob/main/src/Detached.Mappers.EntityFramework/Context/EntityFrameworkMapperContext.cs`

There is a OnMapperAction method, it receives the entity, the DTO, the key and a MapperActionType: Load/Create/Update/Delete.
For Load, a full query is run, in this state, all the entities should be in the ChangeTracker. For the mutation actions, detached tries to get the entity from the change tracker or create a new one, and set the EntityState. That is what you would normally do manually.
I think that you could customize this class to suite your needs, but I need to re-read your sample to tell you exactly what (will do later).
Once you have your customized mapper context, it can be passed to the mapper class without modifying the library. Take a look at https://github.com/leonardoporro/Detached-Mapper/blob/main/src/Detached.Mappers.EntityFramework/Extensions/DbContextExtensions.cs, line 30 to see how.

Anyway Detached does a kind of upsert, need to read your sample later to see why doesn't work, my brain is burnt out now.

**Comment by pinoli** [comment] 2020-10-23 22:36
Amazing @leonardoporro thank you very much for the response.
I will start playing with this right away, to see if I can make it work.

**Comment by leonardoporro** [comment] 2020-10-23 23:22
Violation of PRIMARY KEY constraint 'PK_Users'. happens because the entity is not loaded in the change tracker (so that, it is added again).
If the entity is not in the change tracker, it means that it wasn't loaded by the QueryProvider (that runs for the Load action)
Then, it means the QueryProvider didn't add the corresponding Include.
Finally, the Include was not added because the property is not marked as Composition or Aggregation? The QueryProvider is bugged? ChangeTracker is cleared in any way without calling the query again?

**Comment by leonardoporro** [comment] 2020-10-23 23:26
Also, if you can write a small piece of code to replicate the issue (as I did with the ¨bool¨ issue) and send it to me or make a PR here: https://github.com/leonardoporro/Detached-Mapper/tree/main/test/Detached.Mappers.EntityFramework.Tests, I will surely be able to fix the issue in minutes.

**Comment by pinoli** [comment] 2020-10-24 00:24
@leonardoporro thanks for your precious support.
I think I understand what's going on.
I will try my best to show you what my model looks like: pasting code is not an option since this model is huge, and it's just one of many API endpoint

```
receipt (existing key) (unique)
|__document (existing key) (unique)
   |__list(row) (existing key) (unique)
   |  |
   |  |__row_modifier (no key) (unique)
   |
   |__list(payment) (no key) (unique) <--- PROBLEM 
   |  |
   |  |__custom_payment (existing key) (shared)
   |  |
   |  |__ticket (existing key) (shared)
   |
   |__order_summary (no key) (unique)
   |
   |__user (existing key) (shared)
   |
   |__document_reason (existing key) (shared)
```

You can see from the tree how my parent object is structured.
The problem happens when I create a new Guid for the `payment` objects: these are new objects with new keys, when Detached checks against the DB they are not found. But as you can see, `payment` has children that are shared between `receipts`. At the same time, even if these are new objects, Detached should check for existing children, is this right?

**Comment by pinoli** [comment] 2020-10-24 00:38
responding to https://github.com/leonardoporro/Detached-Mapper/issues/19#issuecomment-715630639
I actually missed one composition, so I thought it could fix it, but I am getting the same issue, primary key violation.

responding to https://github.com/leonardoporro/Detached-Mapper/issues/19#issuecomment-715615656
I looked a bit to the code and I understand there two MapperParameters that change the behavior when loading object into the tracker. [MapperParameters.cs](https://github.com/leonardoporro/Detached-Mapper/blob/6ff6506bdebf541932b92f788ff371fd80b17717/src/Detached.Mappers/MapperParameters.cs)
I surely need `RootUpsert`, and it is on by default I see. I am not sure about `EnsureAggregations `, I am actually using it when mapping, but I don't use any `[Aggregation]`.
I think the behavior is fine and the problem is more on my side.

responding to https://github.com/leonardoporro/Detached-Mapper/issues/19#issuecomment-715630639
I could actually prepare 2 JSON file simulating the two batches and share my code. It could take a little bit, but it can be done. I would appreciate it if you could look at it. Thanks for your kind offering.

**Closed** 2020-10-24 04:32 UTC
Labels: bug
